### PR TITLE
Range select - Changes prescribed by @arkon

### PR DESCRIPTION
**Pull request by hXtreme**

### CODE REVIEW

**Comment by hXtreme** [comment]
@Flat don't merge this yet. I wanted to ask @arkon something regarding this.

**Comment by hXtreme** [comment]
@arkon Currently I've added a single line of code that runs every time a chapter is selected/deselected should I take that line out into its own function?

**Comment by arkon** [comment]
Seems fine to me.

**Comment by hXtreme** [comment]
@Flat feel free to merge.

**Comment by Flat** [comment]
Merged, thanks again for the improvements.

**Pull request merged**
